### ISSUE TITLE
Create GSheets Master Data Framework

### ISSUE THREAD

**Issue by kurodaritsu** [osuph/quickafireee#4]

**Comment by sr229** [comment]
You can make a centralized logic for this (use `sheet_manager.py`).

**Comment by kurodaritsu** [comment]
@sr229 That's what I was planning to do. Though I'm still undecided what columns to add in the master list other than the ones in the submitted forms.

Would try to push and pr later.

**Comment by sr229** [comment]
> Though I'm still undecided what columns to add in the master list other than the ones in the submitted forms.

Consult the tourney team for their requirements, otherwise we can use their existing sheets

**Comment by kurodaritsu** [comment]
Framework created from this link:
https://osuph.topec.nz/forms/quickfire23/

![image](https://user-images.githubusercontent.com/39328974/228220419-84b776d6-89f0-4be8-9961-71d8cebbcff8.png)
